SELECT UNIQUE CD_DEPTO FROM T_SIP_FUNCIONARIO;

SELECT NR_MATRICULA,
    NM_FUNCIONARIO FUNCIONARIO,
    VL_SALARIO_MENSAL "SALARIO MENSAL",
    VL_SALARIO_MENSAL * 1.05 AS "SALARIO REAJUSTADO"
    FROM T_SIP_FUNCIONARIO
ORDER BY "SALARIO REAJUSTADO" DESC;   


-- UTILIZANDO FILTROS
SELECT NR_MATRICULA, NM_FUNCIONARIO, VL_SALARIO_MENSAL
    FROM T_SIP_FUNCIONARIO
WHERE VL_SALARIO_MENSAL > 2000;

-- UTILIZANDO A CONVERSÃO DE TEXTO
SELECT NR_MATRICULA, NM_FUNCIONARIO
  FROM T_SIP_FUNCIONARIO
 WHERE UPPER(NM_FUNCIONARIO) = 'JOAO DA SILVA'; 
-- OU 
 SELECT NR_MATRICULA, NM_FUNCIONARIO
  FROM T_SIP_FUNCIONARIO
 WHERE LOWER(NM_FUNCIONARIO) = 'joao da silva';
 
 -- OPERADOR LOGICO AND -> PRECISA ATENDER AS DUAS CONDIÇÕES 
-- PARA RECUPERAR OS VALORES
SELECT NR_MATRICULA, NM_FUNCIONARIO, CD_DEPTO, DT_ADMISSAO
  FROM T_SIP_FUNCIONARIO
 WHERE DT_ADMISSAO >= TO_DATE('01/08/2015','DD/MM/YYYY') 
       AND CD_DEPTO = 3;
       
-- OPERADOR LOGICO OR -> PRECISA ANTENDER QUALQUER UMA 
-- DAS CONDIÇÕES PARA RECUPERAR OS VALORES
SELECT NR_MATRICULA, NM_FUNCIONARIO, 
       CD_DEPTO, VL_SALARIO_MENSAL
  FROM T_SIP_FUNCIONARIO
 WHERE CD_DEPTO = 4 
 OR VL_SALARIO_MENSAL > 3000;
 
 
 -- OPERADOR NOT
SELECT NR_MATRICULA, NM_FUNCIONARIO, 
 CD_DEPTO, VL_SALARIO_MENSAL
  FROM T_SIP_FUNCIONARIO
 WHERE NOT CD_DEPTO = 4;
 
 
 -- OPERADOR BETWEEN
SELECT NR_MATRICULA, NM_FUNCIONARIO, 
 CD_DEPTO, VL_SALARIO_MENSAL  
FROM   T_SIP_FUNCIONARIO 
WHERE  VL_SALARIO_MENSAL BETWEEN 1000 AND 2500;


-- OPERADOR IN
SELECT NR_MATRICULA, NM_FUNCIONARIO, CD_DEPTO
  FROM   T_SIP_FUNCIONARIO
 WHERE  CD_DEPTO IN (1,2,3);
 
 
 -- OPERADOR IN
SELECT  NR_MATRICULA ,      
  DT_ADMISSAO ,
  VL_SALARIO_MENSAL 
FROM    T_SIP_FUNCIONARIO
WHERE   TO_CHAR(DT_ADMISSAO,'YYYY') IN ('2012','2014');

-- Exemplo utilizando vários operadores
SELECT 	NR_MATRICULA   ,
         CD_DEPTO       ,
         NM_FUNCIONARIO ,
         DT_NASCIMENTO  ,
         DT_ADMISSAO    ,
         VL_SALARIO_MENSAL
  FROM 	T_SIP_FUNCIONARIO
 WHERE   DT_NASCIMENTO 
             BETWEEN 
                 TO_DATE('01/01/1980','DD/MM/YYYY')  
             AND
                 TO_DATE('30/12/2010','DD/MM/YYYY')                   
         AND
          DT_ADMISSAO > TO_DATE('01/01/2013','DD/MM/YYYY')  
         AND VL_SALARIO_MENSAL < 2300 
         AND NOT CD_DEPTO = 3 ;
         
         
-- EXIBIR O TEXTO: "O FUNCIONARIO <NOME> FOI 
-- ADMITIDO EM <DATA ADMISSAO>"
SELECT NR_MATRICULA,
 'O FUNCIONARIO ' || 
 NM_FUNCIONARIO ||
 ', FOI ADMITIDO EM: ' || 
 DT_ADMISSAO "TEXTO"
  FROM T_SIP_FUNCIONARIO;
  
  
-- RESTRINGINDO A QUANTIDADE DE LINHAS RECUPERADAS 
-- DURANTE A CONSULTA
SELECT    NR_MATRICULA ,
    CD_DEPTO ,
    DT_ADMISSAO ,
    VL_SALARIO_MENSAL ,
    (VL_SALARIO_MENSAL * 12) "SALÁRIO ANUAL"
  FROM   T_SIP_FUNCIONARIO
 WHERE  ROWNUM < 4;
 
 
 -- PARA EXIBIR OS NOMES E OS SALÁRIOS DOS 
-- TRÊS FUNCIONÁRIOS MAIS BEM REMUNERADOS 
-- DA TABELA FUNCIONARIO.
SELECT  ROWNUM as RANK , 
               NM_FUNCIONARIO , 
               VL_SALARIO_MENSAL
FROM 
    (    SELECT NM_FUNCIONARIO ,
                VL_SALARIO_MENSAL
           FROM T_SIP_FUNCIONARIO
       ORDER BY VL_SALARIO_MENSAL DESC
    )
WHERE ROWNUM <= 3;


SELECT * FROM T_SIP_PROJETO;

-- Para alterar o formato de exibição de uma data 
-- é utilizado a sintaxe:
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY';


--Para alterar o idioma da data de exibição 
-- é utilizado a sintaxe:
ALTER SESSION SET NLS_DATE_LANGUAGE = 'PORTUGUESE';

-- CONSULTA A DATA SO SERVIDOR
SELECT SYSDATE,
       TO_CHAR(SYSDATE, 'MONTH')
  FROM DUAL;
  
  
  
  -- CONSULTA 
  SELECT CD_PROJETO ,
         CD_IMPLANTACAO ,
         NR_MATRICULA,
         DT_ENTRADA,
         DT_SAIDA,
         ( 'TEMPO DA IMPLANTAÇÃO ( ' || 
           TO_CHAR(SYSDATE - DT_ENTRADA) || 
           ' ) DIAS.'
         ) "TEMPO DE IMPLANTAÇAO"
    FROM T_SIP_IMPLANTACAO
   WHERE DT_SAIDA IS NULL
ORDER BY "TEMPO DE IMPLANTAÇAO" DESC;