CREATE TABLE T_SIP_PROJETO(
    CD_PROJETO NUMBER(5) NOT NULL,
    NM_PROJETO VARCHAR(100) NOT NULL,
    DT_INICIO DATE NOT NULL,
    DT_TERMINO DATE NULL
)


CREATE TABLE T_SIP_COPY_PROJETO_FIN(
    CD_PROJETO NUMBER(5) NOT NULL,
    NM_PROJETO VARCHAR(100) NOT NULL,
    DT_INICIO DATE NOT NULL,
    DT_TERMINO DATE NOT NULL
);


INSERT INTO T_SIP_PROJETO (CD_PROJETO, NM_PROJETO, DT_INICIO) VALUES (2,'PROJETO SVG',TO_DATE('02/01/2024'));

INSERT INTO T_SIP_PROJETO VALUES (1,'PROJETO ABC',TO_DATE('15/02/2024','DD/MM/YYYY'),NULL);

INSERT INTO T_SIP_PROJETO VALUES (3,'PROJETO GIT',TO_DATE('20/02/2024','DD/MM/YYYY'),TO_DATE('27/02/2024','DD/MM/YYYY'));



INSERT INTO T_SIP_COPY_PROJETO_FIN (CD_PROJETO, NM_PROJETO, DT_INICIO, DT_TERMINO)
    (SELECT * 
    FROM T_SIP_PROJETO
    WHERE DT_TERMINO IS NOT NULL);

    SELECT * FROM T_SIP_PROJETO;
    SELECT * FROM T_SIP_COPY_PROJETO_FIN;
    


-- MANIPULACAO DE DADOS
UPDATE T_SIP_PROJETO
SET DT_INICIO = TO_DATE('02/01/2024','DD/MM/YYYY'),
    DT_TERMINO = TO_DATE('02/03/2024','DD/MM/YYYY')
WHERE CD_PROJETO = 2;


CREATE TABLE T_SIP_FUNCIONARIO(
    CD_FUNC NUMBER(3) NOT NULL,
    NM_FUNC VARCHAR(100) NOT NULL,
    VL_SALARIO NUMBER(10,2) NOT NULL
)



INSERT INTO T_SIP_FUNCIONARIO VALUES (2,'FELIPE AUGUSTO',5690.00);


SELECT * FROM T_SIP_FUNCIONARIO;

UPDATE T_SIP_FUNCIONARIO
    SET VL_SALARIO = VL_SALARIO * 1.05;
    
    
-- SETAR UMA DATA EXISTENTE EM UM DADO PARA TODOS
UPDATE T_SIP_PROJETO
    SET DT_TERMINO = 
    (SELECT DT_TERMINO
    FROM T_SIP_COPY_PROJETO_FIN
    WHERE CD_PROJETO = 2)
WHERE DT_TERMINO IS NULL;

SELECT * FROM T_SIP_PROJETO;




-- DELETAR LINHAS


DELETE FROM T_SIP_PROJETO
WHERE DT_INICIO <= TO_DATE('01/02/2024', 'DD/MM/YYYY');

SELECT * FROM T_SIP_PROJETO;

DELETE FROM T_SIP_PROJETO;


COMMIT;