CREATE TABLE T_SIP_TESTE_DDL(
    cd_teste    NUMBER(3) NOT NULL,
    nm_teste    VARCHAR2(50) NULL,
    dt_teste    DATE NOT NULL
);
DROP TABLE T_SIP_TESTE_DDL;

-- ADICIONAR UMA NOVA COLUNA
ALTER TABLE T_SIP_TESTE_DDL 
    ADD DT_DATA DATE NOT NULL;
    
-- ADICONAR DUAS OU MAIS COLUNAS
ALTER TABLE T_SIP_TESTE_DDL 
    ADD (ds_obs1 VARCHAR2(10) NOT NULL, ds_obs2 VARCHAR2(10));
    
-- MODIFICANDO O TAMANHO OU TIPO DE DADO DE UMA COLUNA
ALTER TABLE T_SIP_TESTE_DDL 
    MODIFY ds_obs1 CHAR(20);
    
--  MODIFICANDO UMA COLUNA NULL PARA NOT NULL(OBRIGATORIO) E VICE VERSA
ALTER TABLE T_SIP_TESTE_DDL 
    MODIFY ds_obs2 NOT NULL;
-- PODENDO TUDO SER MODIFICADO EM UM SO CODIGO

-- MODIFICAR UM VALOR DEFAULT
-- SYSDATE - FUNCAO DO ORACLE QUE RETORNA DATA/HORA DO SERVIDOR DE BD
ALTER TABLE T_SIP_TESTE_DDL 
    MODIFY dt_data DEFAULT SYSDATE;
    

-- EXCLUIR COLUNA DA TABELA
ALTER TABLE T_SIP_TESTE_DDL
    DROP COLUMN dt_data;
    
-- EXCLUIR DOIS OU MAIS
ALTER TABLE T_SIP_TESTE_DDL
    DROP (DS_EMAIL, DS_OBS2);
    
-- REMOVER CONSTRAINTS DE CHAVES PRIMARIAS, CHAVES ESTRANGEIRAS, UNIQUE, CHECK   
ALTER TABLE T_SIP_TESTE_DDL
    DROP CONSTRAINT FK_CHAVE_ESTRANGEIRA_EXEMPLO;
    

-- RENOMEAR NOME DA TABELA
ALTER TABLE T_SIP_TESTE_DDL RENAME TO T_TESTE_DDL

-- RENOMEAR NOME DA COLUNA
ALTER TABLE T_SIP_TESTE_DDL
    RENAME COLUMN DS_EMAIL TO DS_EMAIL_NOVO
    
-- RENOMEAR CONSTRAINT
ALTER TABLE T_SIP_TESTE_DDL
    RENAME CONSTRAINT UN_TESTE_DDL_NOME TO UN_TESTE_DDL_NOME_NOVO


-- BLOQUEAR E DESBLOQUEAR UMA CONSTRAINT
-- DISABLE OU ENABLE
ALTER TABLE T_SIP_TESTE_DDL
    DISABLE CONSTRAINT TO UN_TESTE_DDL_NOME_NOVO