-- Elaboração das Querys de Consulta:

-- Comando SQL item a)
SELECT  
    CAT.CD_CATEGORIA,
    CAT.DS_CATEGORIA,
    P.CD_PRODUTO,
    P.DS_PRODUTO,
    P.VL_UNITARIO,
    P.TP_EMBALAGEM,
    P.VL_PERC_LUCRO
FROM 
    MC_CATEGORIA_PROD CAT LEFT JOIN MC_PRODUTO P
    ON CAT.CD_CATEGORIA = P.CD_CATEGORIA
    ORDER BY CAT.CD_CATEGORIA,P.DS_PRODUTO;



-- Comando SQL item b)
SELECT  
    CLI.NR_CLIENTE,
    CLI.NM_CLIENTE,
    CLI.DS_EMAIL,
    CLI.NR_TELEFONE,        
    CLI.NM_LOGIN,
    CF.DT_NASCIMENTO "DT_NASC",
    TO_CHAR(DT_NASCIMENTO, 'D') "DIA_SEMANA_NASC",
    CASE 
        WHEN EXTRACT(MONTH FROM CF.DT_NASCIMENTO) > EXTRACT(MONTH FROM CURRENT_DATE) OR 
             EXTRACT(MONTH FROM CF.DT_NASCIMENTO) = EXTRACT(MONTH FROM CURRENT_DATE) AND 
             EXTRACT(DAY FROM CF.DT_NASCIMENTO) > EXTRACT(DAY FROM CURRENT_DATE)
        THEN (EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM CF.DT_NASCIMENTO)) - 1
        ELSE EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM CF.DT_NASCIMENTO)
    END AS "IDADE",
    CF.FL_SEXO_BIOLOGICO,
    CF.NR_CPF
FROM 
    MC_CLIENTE CLI INNER JOIN MC_CLI_FISICA CF 
    ON CLI.NR_CLIENTE = CF.NR_CLIENTE;



-- Comando SQL item c)  
SELECT 
    VV.CD_PRODUTO,
    P.DS_PRODUTO,
    VV.DT_VISUALIZACAO,
    VV.NR_HORA_VISUALIZACAO || ':' || VV.NR_MINUTO_VIDEO || ':' || VV.NR_SEGUNDO_VIDEO AS HORA_VISUALIZACAO
FROM 
    MC_SGV_VISUALIZACAO_VIDEO VV INNER JOIN MC_PRODUTO P
    ON VV.CD_PRODUTO = P.CD_PRODUTO
    ORDER BY  VV.DT_VISUALIZACAO DESC;