-- COUNT() - CONTAGEM

SELECT COUNT(*) FROM T_SIP_FUNCIONARIO;

SELECT COUNT(DT_TERMINO) FROM T_SIP_PROJETO;

SELECT COUNT(CD_PROJETO)
  FROM T_SIP_PROJETO
 WHERE DT_TERMINO IS NOT NULL;


-- SUM() - SOMATORIA
SELECT SUM(VL_SALARIO_MENSAL)
 FROM T_SIP_FUNCIONARIO;
 
 
-- AVG() - MEDIA
SELECT AVG(VL_SALARIO_MENSAL)
 FROM T_SIP_FUNCIONARIO;
 
 -- MIN(), MAX() - MENOR E MAIOR VALOR
SELECT MIN(VL_SALARIO_MENSAL)
 FROM T_SIP_FUNCIONARIO;
 
SELECT MAX(VL_SALARIO_MENSAL)
 FROM T_SIP_FUNCIONARIO;
 
 
-- STDDEV() - DESVIO PADRAO
SELECT STDDEV(VL_SALARIO_MENSAL)
 FROM T_SIP_FUNCIONARIO;
 
 -- VARIANCE() - VARIANCIA
SELECT VARIANCE(VL_SALARIO_MENSAL)
 FROM T_SIP_FUNCIONARIO;
 
 
 
 
 
 
 
 
 
 
 
 --  GROUP BY 
SELECT NR_MATRICULA, COUNT(CD_DEPENDENTE) "QTDE. DEPENDENTES"
  FROM T_SIP_DEPENDENTE
    GROUP BY NR_MATRICULA;
    
--  TUDO QUE NAO FOR FUNCAO DE GRUPO, COMO COUNT(), PRECISA ESTAR NO GROUP BY, COMO O NR_MATRICULA

--EXEMPLO DE ERRO, POIS O NM_DEPENDENTE NAO ESTA NO GROUP BY
SELECT NR_MATRICULA, NM_DEPENDENTE, COUNT(CD_DEPENDENTE) "QTDE. DEPENDENTES"
  FROM T_SIP_DEPENDENTE
    GROUP BY NR_MATRICULA;
    
    
    
-- EXEMPLO – GROUP BY COM FUNÇÃO DE GRUPO
  SELECT CD_DEPTO,
   COUNT(NR_MATRICULA) "QTDE. FUNCIONARIOS NO DEPTO",
   SUM(VL_SALARIO_MENSAL) "TOTAL SALARIO POR DEPTO",
   ROUND(AVG(VL_SALARIO_MENSAL),2) "MEDIA SALARIAL POR DEPTO"
    FROM T_SIP_FUNCIONARIO
GROUP BY CD_DEPTO
ORDER BY CD_DEPTO;
-- EXIBIRA INFOS POR CADA DEPARTAMENTO



-- EXEMPLO – GROUP BY COM VÁRIAS TABELAS
SELECT F.NM_FUNCIONARIO       "FUNCIONARIO" ,
       D.NR_MATRICULA         "MATRICULA"   , 
       COUNT(D.NR_MATRICULA)  "QTDE. DEPENDENTES"
  FROM T_SIP_FUNCIONARIO F INNER JOIN T_SIP_DEPENDENTE D
       ON (F.NR_MATRICULA = D.NR_MATRICULA)
    GROUP BY F.NM_FUNCIONARIO, D.NR_MATRICULA;
-- QUANTOS DEPENDENTES CADA FUNCIONARIO POSSUI



-- EXEMPLO – GROUP BY COM HAVING
  SELECT CD_DEPTO,
   COUNT(NR_MATRICULA) "QTDE. FUNCIONARIO NO DEPTO",
   SUM(VL_SALARIO_MENSAL) "TOTAL SALARIO POR DEPTO",
   ROUND(AVG(VL_SALARIO_MENSAL),2) "MEDIA SALARIAL POR DEPTO"
    FROM T_SIP_FUNCIONARIO
GROUP BY CD_DEPTO
    HAVING SUM(VL_SALARIO_MENSAL) > 10000;
-- USANDO O HAVING, EXIBIRA APENAS OS DEPTOS ONDE A SOMATORIA DOS SALARIOS FOR MAIS DE 10.000


-- EXEMPLO DE ERRO, O WHERE NAO É USADO PARA FILTRAR GRUPOS, OCASINANDO EM ERRO
  SELECT CD_DEPTO,
   COUNT(NR_MATRICULA) "QTDE. FUNCIONARIO NO DEPTO",
   SUM(VL_SALARIO_MENSAL) "TOTAL SALARIO POR DEPTO",
   ROUND(AVG(VL_SALARIO_MENSAL),2) "MEDIA SALARIAL POR DEPTO"
    FROM T_SIP_FUNCIONARIO
GROUP BY CD_DEPTO
 WHERE SUM(VL_SALARIO_MENSAL) > 10000;
 
 
 
 
 -- EXEMPLO – INSTRUÇÃO CASE
SELECT
        NM_PROJETO,
        DT_TERMINO,
CASE
  WHEN DT_TERMINO IS NULL THEN 'EM ANDAMENTO'
  ELSE 'FINALIZADO'
END STATUS_PROJETO
  FROM T_SIP_PROJETO
ORDER BY NM_PROJETO;
-- END DEFINE O NOME DA COLUNA E O THEN O RETORNO DA COLUNA SE A DATA FOR NULA









-- CONSULTA 1
SELECT MAX(DT_SAIDA - DT_ENTRADA) || ' DIAS' AS DURAÇÃO
  FROM T_SIP_IMPLANTACAO;
-- IMPLANTACAO COM MAIOR DURACAO



-- CONSULTA 2
  SELECT F.CD_DEPTO, D.NM_DEPTO,
         ROUND(AVG(VL_SALARIO_MENSAL),2) "MÉDIA SALARIAL POR DEPTO"
    FROM T_SIP_DEPARTAMENTO D INNER JOIN T_SIP_FUNCIONARIO F
         ON (D.CD_DEPTO = F.CD_DEPTO)
GROUP BY F.CD_DEPTO, D.NM_DEPTO
ORDER BY "MÉDIA SALARIAL POR DEPTO" DESC;
-- COMPARA O CD_DEPTO AGRUPANDO A MEDIA DE SALARIO DOS FUNCIONARIOS DE CADA DEPTO



-- CONSULTA 3
  SELECT I.CD_PROJETO, P.NM_PROJETO,
         COUNT (I.CD_IMPLANTACAO) "QTDE.  IMPLANTAÇÕES"
    FROM T_SIP_PROJETO P INNER JOIN T_SIP_IMPLANTACAO I
         ON (P.CD_PROJETO = I.CD_PROJETO)
GROUP BY I.CD_PROJETO, P.NM_PROJETO;
-- EXIBE QUANTAS IMPLANTACOES CADA PROJETO POSSUI



-- CONSULTA 4
  SELECT I.CD_PROJETO, P.NM_PROJETO,
         COUNT (I.CD_IMPLANTACAO) "QTDE. IMPLANTAÇÕES EM ANDAMENTO"
    FROM T_SIP_PROJETO P INNER JOIN T_SIP_IMPLANTACAO I
         ON (P.CD_PROJETO = I.CD_PROJETO)
   WHERE I.DT_SAIDA IS NULL
GROUP BY I.CD_PROJETO, P.NM_PROJETO;
-- EXIBE QUANTAS IMPLANTACOES ESTAO EM ANDAMENTO, QUANDO A DATA DE SAIDA É NULA
-- AQUI O WHERE PODE SER USADO POIS NAO ESTA FILTRANDO UM GRUPO, USANDO NENHUMA FUNCAO DE FILTRO, APENAS UMA VALIDACAO



-- CONSULTA 5
  SELECT I.CD_PROJETO, P.NM_PROJETO,
         COUNT (I.CD_IMPLANTACAO) "QTDE. IMPLANTAÇÕES FINALIZADAS"
    FROM T_SIP_PROJETO P INNER JOIN T_SIP_IMPLANTACAO I
         ON (P.CD_PROJETO = I.CD_PROJETO)
   WHERE I.DT_SAIDA IS NOT NULL
GROUP BY I.CD_PROJETO, P.NM_PROJETO
ORDER BY NM_PROJETO;
-- EXIBE QUANTAS IMPLANTACOES ESTAO FINALIZADAS



-- CONSULTA 6
  SELECT I.NR_MATRICULA, F.NM_FUNCIONARIO,
         COUNT (I.CD_IMPLANTACAO) "QTDE.  IMPLANTAÇÕES"
    FROM T_SIP_FUNCIONARIO F INNER JOIN T_SIP_IMPLANTACAO I
         ON (F.NR_MATRICULA = I.NR_MATRICULA)
GROUP BY I.NR_MATRICULA, F.NM_FUNCIONARIO;
-- QUANTAS IMPLEMENTACOES FORAM FEITAS POR CADA FUNCIONARIO


-- A PARTE
-- IMPLEMENTACOES  JA REALIZADAS DE CADA FUNCIONARIO, DT_SAIDA DEFINIDA
  SELECT I.NR_MATRICULA, F.NM_FUNCIONARIO,
         COUNT (I.CD_IMPLANTACAO) "QTDE.  IMPLANTAÇÕES"
    FROM T_SIP_FUNCIONARIO F INNER JOIN T_SIP_IMPLANTACAO I
         ON (F.NR_MATRICULA = I.NR_MATRICULA)
    WHERE(I.DT_SAIDA IS NOT NULL)
GROUP BY I.NR_MATRICULA, F.NM_FUNCIONARIO;