-- EXEMPLO – SUBCONSULTA DE UMA ÚNICA LINHA,
-- COM FUNÇÕES DE GRUPO
SELECT F.NM_FUNCIONARIO,
    F.VL_SALARIO_MENSAL
  FROM T_SIP_FUNCIONARIO F
 WHERE F.VL_SALARIO_MENSAL > (
                        SELECT AVG(F.VL_SALARIO_MENSAL)
                        FROM T_SIP_FUNCIONARIO F
                      );
-- EXIBE OS FUNCIONARIOS QUE TEM O SALARIO MAIOR QUE A MEDIA DOS SALARIOS



-- EXEMPLO – SUBCONSULTA DE UMA ÚNICA LINHA,
 -- COM AGRUPAMENTO, FUNÇÕES DE GRUPO E HAVING
   SELECT CD_DEPTO,
          MIN(VL_SALARIO_MENSAL)
     FROM T_SIP_FUNCIONARIO 
 GROUP BY CD_DEPTO
   HAVING MIN(VL_SALARIO_MENSAL) > (
                                 SELECT MIN(VL_SALARIO_MENSAL)
                                   FROM T_SIP_FUNCIONARIO 
                                  WHERE CD_DEPTO = 3 
                        );
-- SUBCONSULTA TRAS O MENOR SALARIO DE DETERMINADO DEPTO
-- CONSULTA PRINCIPAL TRAS OS DEPTOS QUE POSSUEM O MENOR SALARIO, SENDO MAIOR QUE O SALARIO DO DEPTO 3, DA SUBCONSULTA





-- EXEMPLO – SUBCONSULTA DE UMA ÚNICA LINHA,
 -- COM CLÁUSULA FROM
   SELECT F.NR_MATRICULA ,
          F.NM_FUNCIONARIO , 
          F.DT_ADMISSAO  , 
          RESFUNC.QTDEALOCACAO
   FROM   T_SIP_FUNCIONARIO F , 
                         (
                          SELECT  NR_MATRICULA , 
                                    COUNT(NR_MATRICULA) QTDEALOCACAO
                              FROM  T_SIP_IMPLANTACAO  
                          GROUP BY  NR_MATRICULA                                  
                          ) RESFUNC
                               
  WHERE F.NR_MATRICULA = RESFUNC.NR_MATRICULA ;
  -- RESFUNC É UMA NOVA TABELA, ONDE AGRUPA QUANTAS IMPLANTACOES CADA FUNCIONARIO FEZ
  
  
  
  
  
  
  
  
  

  -- EXEMPLO – SUBCONSULTA COM VÁRIAS LINHAS,
 -- COM OPERADOR IN
 SELECT CD_IMPLANTACAO ,
        CD_PROJETO     , 
  NR_MATRICULA "FUNCIONARIO"
   FROM T_SIP_IMPLANTACAO 
  WHERE CD_PROJETO IN
           (
             SELECT CD_PROJETO
               FROM T_SIP_PROJETO 
                    WHERE TO_CHAR(DT_INICIO,'MM/YYYY') IN('04/2012','10/2013')
                  );
                  
-- NAO PODERIA SER USADO OPERADOR RELACIONAL(>=, <, ETC), POIS A SUBCONSULTA RETORNA MAIS DE UMA LINHA
-- ENTAO DEVE-SE USAR IN, NOT IN, ANY, ALL
-- ESSE CASO TRAS OS PROJETOS QUE ESTAO ENTRE(IN) A DATA SELECIONADA NA SUBCONSULTA



-- EXEMPLO – SUBCONSULTA COM VÁRIAS LINHAS,
 -- COM OPERADOR NOT IN
 SELECT CD_IMPLANTACAO ,
        CD_PROJETO     , 
  NR_MATRICULA "FUNCIONARIO"
   FROM T_SIP_IMPLANTACAO 
  WHERE CD_PROJETO NOT IN
           (
             SELECT CD_PROJETO
               FROM T_SIP_PROJETO 
                    WHERE TO_CHAR(DT_INICIO,'MM/YYYY') IN('04/2012','10/2013')
                  );
                  
 -- ESSE CASO TRAS OS PROJETOS QUE NAO ESTAO ENTRE(NOT IN) A DATA SELECIONADA NA SUBCONSULTA
 
 
 
 -- EXEMPLO – SUBCONSULTA COM VÁRIAS LINHAS,
 -- COM OPERADOR ANY
 SELECT NR_MATRICULA   , 
        NM_FUNCIONARIO , 
        VL_SALARIO_MENSAL
   FROM T_SIP_FUNCIONARIO 
  WHERE VL_SALARIO_MENSAL < ANY 
                          (
                               SELECT AVG(VL_SALARIO_MENSAL)
                                 FROM T_SIP_FUNCIONARIO 
                             GROUP BY CD_DEPTO
                           );
--SUBCONSULTA TRAS A MEDIA SALARIAL DE CADA DEPTO
-- CONSULTA PRINCIPAL LISTA TODOS OS FUNCIONARIOS CUJO SALARIO É MENOR QUE QUALQUER UMA DAS MEDIAS SALARIAIS
-- ANY = QUALQUER UMA



-- EXEMPLO – SUBCONSULTA COM VÁRIAS LINHAS,
 -- COM OPERADOR ALL
 SELECT NR_MATRICULA   , 
        NM_FUNCIONARIO , 
        VL_SALARIO_MENSAL
   FROM T_SIP_FUNCIONARIO 
  WHERE VL_SALARIO_MENSAL > ALL 
                          (
                               SELECT AVG(VL_SALARIO_MENSAL)
                                 FROM T_SIP_FUNCIONARIO 
                             GROUP BY CD_DEPTO
                           );
--SUBCONSULTA TRAS A MEDIA SALARIAL DE CADA DEPTO
-- CONSULTA PRINCIPAL LISTA TODOS OS FUNCIONARIOS CUJO SALARIO É MAIOR QUE TODAS MEDIAS SALARIAIS
-- ANY = TODAS




-- EXEMPLO – SUBCONSULTA CORRELACIONADA,
-- COM EXISTS
 SELECT F.NR_MATRICULA,
     F.NM_FUNCIONARIO
  FROM T_SIP_FUNCIONARIO F
 WHERE EXISTS
            (
              SELECT I.NR_MATRICULA
                FROM T_SIP_IMPLANTACAO I
               WHERE F.NR_MATRICULA=I.NR_MATRICULA
            );
-- SUBCONSULTA CORRELACIONADAS NAO PODEM SER EXECUTADAS SEM A PRINCIPAL, NECESSITA DELA
-- CONSULTA PRINCIPAL TRAS OS FUNCIONARIOS QUE EXISTEM NO RESULTADO DA SUBCONSULTA
-- UMA SE COMPARA COM A OUTRA


-- EXEMPLO – SUBCONSULTA CORRELACIONADA,
-- COM NOT EXISTS
SELECT F.NR_MATRICULA,
       F.NM_FUNCIONARIO
  FROM T_SIP_FUNCIONARIO F
 WHERE NOT EXISTS
         (
          SELECT I.NR_MATRICULA
            FROM T_SIP_IMPLANTACAO I
           WHERE F.NR_MATRICULA=I.NR_MATRICULA
         );
-- TRAS OS FUNCIONARIOS QUE NAO EXISTEM NO RESULTADO DA SUBCONSULTA









-- CONSULTA 1
SELECT F.NM_FUNCIONARIO, F.DT_ADMISSAO, RESULT.QTDEPENDENTES
    FROM T_SIP_FUNCIONARIO F, (
                                SELECT NR_MATRICULA,
                                        COUNT(NR_MATRICULA) QTDEPENDENTES
                                FROM T_SIP_DEPENDENTE
                                GROUP BY NR_MATRICULA
                                ) RESULT
WHERE F.NR_MATRICULA = RESULT.NR_MATRICULA;



-- CONSULTA 2
SELECT NR_MATRICULA, NM_FUNCIONARIO, 
       DT_ADMISSAO, VL_SALARIO_MENSAL
  FROM T_SIP_FUNCIONARIO
 WHERE VL_SALARIO_MENSAL > 
    (SELECT MAX(RESULT.MEDIA)
       FROM
            (SELECT CD_DEPTO, 
                    ROUND(AVG(VL_SALARIO_MENSAL),2) MEDIA
               FROM T_SIP_FUNCIONARIO
           GROUP BY CD_DEPTO) RESULT);
           
           
           
-- CONSULTA 3
SELECT NR_MATRICULA, NM_FUNCIONARIO
  FROM T_SIP_FUNCIONARIO
 WHERE NR_MATRICULA IN 
        (SELECT NR_MATRICULA
          FROM T_SIP_IMPLANTACAO 
         WHERE TO_CHAR(DT_ENTRADA,'YYYY') IN ('2016','2017')
         );